package com.pprl.util;




import java.sql.Connection;
import java.sql.DriverManager;
 
public class DBConnection {
	public static Connection createConnection() {
		Connection con = null;
		String url = "jdbc:mysql://faure:3306/diptendu"; // MySQL URL and
																// followed by
																// the database
																// name
		String username = "redacted"; // MySQL username
		String password = "redacted"; // MySQL password

		try {
			try {
				Class.forName("com.mysql.jdbc.Driver"); // loading mysql driver
			} catch (ClassNotFoundException e) {
				e.printStackTrace();
			}
			con = DriverManager.getConnection(url, username, password); 
			//System.out.println("Printing connection object " + con);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return con;
	}
}


// ALL TABLES
/*
+--------------------+
| Tables_in_diptendu |
+--------------------+
| broker_mapping     |
| enc_temp_p1        |
| enc_temp_p2        |
| enc_temp_p3        |
| enc_temp_p4        |
| p1_mapping         |
| p1table            |
| p2_mapping         |
| p2table            |
| p3_mapping         |
| p3table            |
| p4_mapping         |
| p4table            |
| p5_mapping         |
| p6_mapping         |
| t_broker_data      |
| temp_p1            |
| temp_p2            |
| temp_p3            |
| temp_p4            |
| temp_p5            |
| temp_p6            |
| testp1table        |
| testp2table        |
| testp3table        |
| testp4table        |
+--------------------+



// ALL SCHEMA




+---------------+--------------+----------------+---------------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+-------------------+---------------+------------+-------+---------------------------------+----------------+--------------+-----------------------+
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME     | COLUMN_NAME         | ORDINAL_POSITION | COLUMN_DEFAULT | IS_NULLABLE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_NAME | COLLATION_NAME    | COLUMN_TYPE   | COLUMN_KEY | EXTRA | PRIVILEGES                      | COLUMN_COMMENT | IS_GENERATED | GENERATION_EXPRESSION |
+---------------+--------------+----------------+---------------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+-------------------+---------------+------------+-------+---------------------------------+----------------+--------------+-----------------------+
| def           | diptendu     | broker_mapping | BROKER_GENERATED_ID |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | broker_mapping | INCOMING_ID         |                2 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | broker_mapping | SOURCE              |                3 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | enc_temp_p1    | ID                  |                1 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p1    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p1    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p1    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | enc_temp_p2    | ID                  |                1 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p2    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p2    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p2    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | enc_temp_p3    | ID                  |                1 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p3    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p3    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p3    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | enc_temp_p4    | ID                  |                1 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p4    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p4    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | enc_temp_p4    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p1_mapping     | PLAINTEXT_ID        |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p1_mapping     | ENCR_ID             |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p1table        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p1table        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p1table        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p1table        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p2_mapping     | PLAINTEXT_ID        |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p2_mapping     | ENCR_ID             |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p2table        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p2table        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p2table        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p2table        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p3_mapping     | PLAINTEXT_ID        |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p3_mapping     | ENCR_ID             |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p3table        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p3table        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p3table        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p3table        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p4_mapping     | PLAINTEXT_ID        |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p4_mapping     | ENCR_ID             |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p4table        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p4table        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p4table        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p4table        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p5_mapping     | PLAINTEXT_ID        |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p5_mapping     | ENCR_ID             |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | p6_mapping     | PLAINTEXT_ID        |                1 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | p6_mapping     | ENCR_ID             |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | t_broker_data  | ID                  |                1 | NULL           | NO          | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | t_broker_data  | NAME                |                2 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | t_broker_data  | ADDRESS             |                3 | NULL           | YES         | text      |                    65535 |                  65535 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | text          |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | t_broker_data  | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                      255 |                    255 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | t_broker_data  | TREATMENT           |                5 | NULL           | YES         | varchar   |                      255 |                    255 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | t_broker_data  | COMMENTS            |                6 | NULL           | YES         | varchar   |                      255 |                    255 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | t_broker_data  | SOURCE              |                7 | NULL           | YES         | varchar   |                     2550 |                   2550 |              NULL |          NULL |               NULL | latin1             | latin1_swedish_ci | varchar(2550) |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | temp_p1        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p1        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p1        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p1        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p1        | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p1        | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | temp_p2        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p2        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p2        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p2        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p2        | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p2        | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | temp_p3        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p3        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p3        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p3        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p3        | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p3        | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | temp_p4        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p4        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p4        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p4        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p4        | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p4        | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | temp_p5        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p5        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p5        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p5        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p5        | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p5        | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | temp_p6        | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(11)       |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p6        | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p6        | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p6        | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p6        | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | temp_p6        | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | testp1table    | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(100)      | PRI        |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp1table    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp1table    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp1table    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp1table    | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp1table    | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | testp2table    | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(100)      | PRI        |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp2table    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp2table    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp2table    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp2table    | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp2table    | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | testp3table    | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(100)      | PRI        |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp3table    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp3table    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp3table    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp3table    | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp3table    | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |

| def           | diptendu     | testp4table    | ID                  |                1 | NULL           | NO          | int       |                     NULL |                   NULL |                10 |             0 |               NULL | NULL               | NULL              | int(100)      | PRI        |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp4table    | NAME                |                2 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp4table    | ADDRESS             |                3 | NULL           | YES         | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp4table    | DIAGNOSIS           |                4 | NULL           | YES         | varchar   |                       50 |                    150 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(50)   |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp4table    | TREATMENT           |                5 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
| def           | diptendu     | testp4table    | COMMENTS            |                6 | NULL           | NO          | varchar   |                      255 |                    765 |              NULL |          NULL |               NULL | utf8               | utf8_general_ci   | varchar(255)  |            |       | select,insert,update,references |                | NEVER        | NULL                  |
+---------------+--------------+----------------+---------------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+-------------------+---------------+------------+-------+---------------------------------+----------------+--------------+-----------------------+

*/